# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seleniumserver.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14seleniumserver.proto\x12\x07selserv\"\x17\n\x08HtmlArgs\x12\x0b\n\x03Url\x18\x01 \x01(\t\"\x1c\n\x0cHtmlResponse\x12\x0c\n\x04Html\x18\x01 \x01(\t2E\n\x0eSeleniumServer\x12\x33\n\x07GetHtml\x12\x11.selserv.HtmlArgs\x1a\x15.selserv.HtmlResponseB2Z0github.com/FishyFish3r/crypto-parser/pkg/selservb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seleniumserver_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0github.com/FishyFish3r/crypto-parser/pkg/selserv'
  _HTMLARGS._serialized_start=33
  _HTMLARGS._serialized_end=56
  _HTMLRESPONSE._serialized_start=58
  _HTMLRESPONSE._serialized_end=86
  _SELENIUMSERVER._serialized_start=88
  _SELENIUMSERVER._serialized_end=157
# @@protoc_insertion_point(module_scope)
